# Generated by Django 3.1.5 on 2021-01-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_Promoted', models.BooleanField(default=False)),
                ('types', models.ManyToManyField(related_name='articles', to='article_types.ArticleType')),
            ],
        ),
    ]
