# Generated by Django 3.1.5 on 2021-01-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210131_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subheadline',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
