# Generated by Django 3.1.5 on 2021-02-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_subheadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='favorited_by',
            new_name='favorites',
        ),
    ]
